version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: spikeflow-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: khushal3526
      POSTGRES_DB: spikeflow

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine

    container_name: spikeflow-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

  spikeflow:
    build:
      context: ./gateway
      dockerfile: Dockerfile

    container_name: spikeflow

    restart: unless-stopped

    depends_on:
      - postgres
      - redis

    env_file:
      - ./gateway/.env.docker

    ports:
      - "4000:4000"

    working_dir: /app

  nginx:
    image: nginx:alpine

    container_name: spikeflow-nginx

    restart: unless-stopped

    depends_on:
      - spikeflow

    ports:
      - "80:80"

    volumes:
      - ./nginx/spikeflow.conf:/etc/nginx/conf.d/default.conf:ro  

volumes:
  postgres_data:
  redis_data: